### PR TITLE
Nuke manual entries

### PR DESCRIPTION
**Pull request by nnyyxxxx**
abandon all hope ye who enters

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
relies on https://github.com/hyprwm/Hyprland/pull/7377

**Comment by nnyyxxxx** [comment]
w..i..p..

**Comment by adamperkowski** [comment]
nice

**Comment by nnyyxxxx** [comment]
lets just do it manual for now, way too many problems with automatically generating everything

**Pull request closed without merging**
