### PR TITLE
Add HYPRLAND_CONFIG for custom config path

### LINKED ISSUE #78: [New Feature] Custom hyprland.conf path
Firstly cool project.

Secondly I was wondering if the .conf path could be more flexible I was thinking the [official](https://wiki.hyprland.org/Configuring/Environment-variables/) env var `HYPRLAND_CONFIG` and if it doesn't exist fallback to `.config/hypr/hyprland.conf` .

best way I can think would be to do something like this.
```rust
fn get_config_path() -> PathBuf {
    // Check the environment variable `HYPRLAND_CONFIG`
    if let Ok(config_path) = env::var("HYPRLAND_CONFIG") {
        let path = PathBuf::from(config_path);
        if path.exists() {
            return path;
        }
    }
    // Fallback to the default configuration path
    dirs::home_dir().unwrap().join(".config/hypr/hyprland.conf")
}
```

instead of the hard coded `const CONFIG_PATH: &str = ".config/hypr/hyprland.conf";`

Use case for this 
people that use stow to manage there dots or nix flake users that sim-link using home manager.

### PR DESCRIPTION
**Pull request by mrfluffy-dev**
here is the code for #78 all that is needed is for `HYPRLAND_CONFIG` to be set and if it is not it will go on as it always did.

closes #78

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
please remove the comments

**Comment by nnyyxxxx** [comment]
i would rather this be turned into a button in the settings menu as well that brings up a file picker allowing the user to graphically pick where their config file is

**Comment by mrfluffy-dev** [comment]
Yeah I am going to have no idea how to do that sadly :)

**Comment by nnyyxxxx** [comment]
> Yeah I am going to have no idea how to do that sadly :)

https://doc.rust-lang.org/stable/book/

https://gtk-rs.org/gtk4-rs/stable/latest/book/introduction.html

here are some websites to get started

**Comment by mrfluffy-dev** [comment]
Rust I know its GTK and the source code haha thanks Ill take a look at the GTK docs

**Pull request closed without merging**
